use_frameworks!
#platform :ios, '8.0'

target 'Goji' do
	pod 'Firebase/Storage'
	pod 'Firebase/AdMob'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/Database'
	pod 'Firebase/RemoteConfig'
end
